//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAC.ServiceSGP {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gendarmeria.org/", ConfigurationName="ServiceSGP.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformado(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformado", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadoAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Persona", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Persona(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Persona", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PersonaAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU_like_Descrip_nombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Unidades_OU_like_Descrip_nombre(string p1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU_like_Descrip_nombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OU_like_Descrip_nombreAsync(string p1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UNIDADES_OT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UNIDADES_OT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UNIDADES_OT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UNIDADES_OTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/GRADOS_OT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GRADOS_OT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/GRADOS_OT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GRADOS_OTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UNIDADES_COBRO_OT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UNIDADES_COBRO_OT();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UNIDADES_COBRO_OT", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UNIDADES_COBRO_OTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Unidades_OU(string Cod_Uni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OUAsync(string Cod_Uni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU_POR_ID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Unidades_OU_POR_ID(string Cod_Uni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Unidades_OU_POR_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OU_POR_IDAsync(string Cod_Uni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/PersonalSeguro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PersonalSeguro(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/PersonalSeguro", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PersonalSeguroAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadocompletoAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadoConCivil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UniformadoConCivil(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadoConCivil", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadoConCivilAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto2(string strApenom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto2", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto2Async(string strApenom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_CE(string CE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CE", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CEAsync(string CE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CE_DNI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_CE_DNI(string CE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CE_DNI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CE_DNIAsync(string CE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_DOCUMENTO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_DOCUMENTO(string DOCUMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_DOCUMENTO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_DOCUMENTOAsync(string DOCUMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_CADENA(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENAAsync(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA_COMPLETO", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_CADENA_COMPLETO(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA_COMPLETO", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENA_COMPLETOAsync(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA_DNI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Uniformadocompleto_CADENA_DNI(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Uniformadocompleto_CADENA_DNI", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENA_DNIAsync(string CADENA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadocompletoLikeApeNom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UniformadocompletoLikeApeNom(string strApenom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadocompletoLikeApeNom", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadocompletoLikeApeNomAsync(string strApenom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/WS_HC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet WS_HC(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/WS_HC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> WS_HCAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Foto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Foto(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/Foto", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> FotoAsync(string strDNI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UniformadosDependientes(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependientes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependientesAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependientesRecursivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UniformadosDependientesRecursivo(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependientesRecursivo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependientesRecursivoAsync(string dni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependeDe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet UniformadosDependeDe(string dni, string dni2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gendarmeria.org/UniformadosDependeDe", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependeDeAsync(string dni, string dni2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SAC.ServiceSGP.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SAC.ServiceSGP.ServiceSoap>, SAC.ServiceSGP.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Uniformado(string strDNI) {
            return base.Channel.Uniformado(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadoAsync(string strDNI) {
            return base.Channel.UniformadoAsync(strDNI);
        }
        
        public System.Data.DataSet Persona(string strDNI) {
            return base.Channel.Persona(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PersonaAsync(string strDNI) {
            return base.Channel.PersonaAsync(strDNI);
        }
        
        public System.Data.DataSet Unidades_OU_like_Descrip_nombre(string p1) {
            return base.Channel.Unidades_OU_like_Descrip_nombre(p1);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OU_like_Descrip_nombreAsync(string p1) {
            return base.Channel.Unidades_OU_like_Descrip_nombreAsync(p1);
        }
        
        public System.Data.DataSet UNIDADES_OT() {
            return base.Channel.UNIDADES_OT();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UNIDADES_OTAsync() {
            return base.Channel.UNIDADES_OTAsync();
        }
        
        public System.Data.DataSet GRADOS_OT() {
            return base.Channel.GRADOS_OT();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GRADOS_OTAsync() {
            return base.Channel.GRADOS_OTAsync();
        }
        
        public System.Data.DataSet UNIDADES_COBRO_OT() {
            return base.Channel.UNIDADES_COBRO_OT();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UNIDADES_COBRO_OTAsync() {
            return base.Channel.UNIDADES_COBRO_OTAsync();
        }
        
        public System.Data.DataSet Unidades_OU(string Cod_Uni) {
            return base.Channel.Unidades_OU(Cod_Uni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OUAsync(string Cod_Uni) {
            return base.Channel.Unidades_OUAsync(Cod_Uni);
        }
        
        public System.Data.DataSet Unidades_OU_POR_ID(string Cod_Uni) {
            return base.Channel.Unidades_OU_POR_ID(Cod_Uni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Unidades_OU_POR_IDAsync(string Cod_Uni) {
            return base.Channel.Unidades_OU_POR_IDAsync(Cod_Uni);
        }
        
        public System.Data.DataSet PersonalSeguro(string strDNI) {
            return base.Channel.PersonalSeguro(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PersonalSeguroAsync(string strDNI) {
            return base.Channel.PersonalSeguroAsync(strDNI);
        }
        
        public System.Data.DataSet Uniformadocompleto(string strDNI) {
            return base.Channel.Uniformadocompleto(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadocompletoAsync(string strDNI) {
            return base.Channel.UniformadocompletoAsync(strDNI);
        }
        
        public System.Data.DataSet UniformadoConCivil(string strDNI) {
            return base.Channel.UniformadoConCivil(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadoConCivilAsync(string strDNI) {
            return base.Channel.UniformadoConCivilAsync(strDNI);
        }
        
        public System.Data.DataSet Uniformadocompleto2(string strApenom) {
            return base.Channel.Uniformadocompleto2(strApenom);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto2Async(string strApenom) {
            return base.Channel.Uniformadocompleto2Async(strApenom);
        }
        
        public System.Data.DataSet Uniformadocompleto_CE(string CE) {
            return base.Channel.Uniformadocompleto_CE(CE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CEAsync(string CE) {
            return base.Channel.Uniformadocompleto_CEAsync(CE);
        }
        
        public System.Data.DataSet Uniformadocompleto_CE_DNI(string CE) {
            return base.Channel.Uniformadocompleto_CE_DNI(CE);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CE_DNIAsync(string CE) {
            return base.Channel.Uniformadocompleto_CE_DNIAsync(CE);
        }
        
        public System.Data.DataSet Uniformadocompleto_DOCUMENTO(string DOCUMENTO) {
            return base.Channel.Uniformadocompleto_DOCUMENTO(DOCUMENTO);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_DOCUMENTOAsync(string DOCUMENTO) {
            return base.Channel.Uniformadocompleto_DOCUMENTOAsync(DOCUMENTO);
        }
        
        public System.Data.DataSet Uniformadocompleto_CADENA(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENA(CADENA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENAAsync(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENAAsync(CADENA);
        }
        
        public System.Data.DataSet Uniformadocompleto_CADENA_COMPLETO(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENA_COMPLETO(CADENA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENA_COMPLETOAsync(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENA_COMPLETOAsync(CADENA);
        }
        
        public System.Data.DataSet Uniformadocompleto_CADENA_DNI(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENA_DNI(CADENA);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Uniformadocompleto_CADENA_DNIAsync(string CADENA) {
            return base.Channel.Uniformadocompleto_CADENA_DNIAsync(CADENA);
        }
        
        public System.Data.DataSet UniformadocompletoLikeApeNom(string strApenom) {
            return base.Channel.UniformadocompletoLikeApeNom(strApenom);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadocompletoLikeApeNomAsync(string strApenom) {
            return base.Channel.UniformadocompletoLikeApeNomAsync(strApenom);
        }
        
        public System.Data.DataSet WS_HC(string strDNI) {
            return base.Channel.WS_HC(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> WS_HCAsync(string strDNI) {
            return base.Channel.WS_HCAsync(strDNI);
        }
        
        public System.Data.DataSet Foto(string strDNI) {
            return base.Channel.Foto(strDNI);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> FotoAsync(string strDNI) {
            return base.Channel.FotoAsync(strDNI);
        }
        
        public System.Data.DataSet UniformadosDependientes(string dni) {
            return base.Channel.UniformadosDependientes(dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependientesAsync(string dni) {
            return base.Channel.UniformadosDependientesAsync(dni);
        }
        
        public System.Data.DataSet UniformadosDependientesRecursivo(string dni) {
            return base.Channel.UniformadosDependientesRecursivo(dni);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependientesRecursivoAsync(string dni) {
            return base.Channel.UniformadosDependientesRecursivoAsync(dni);
        }
        
        public System.Data.DataSet UniformadosDependeDe(string dni, string dni2) {
            return base.Channel.UniformadosDependeDe(dni, dni2);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> UniformadosDependeDeAsync(string dni, string dni2) {
            return base.Channel.UniformadosDependeDeAsync(dni, dni2);
        }
    }
}
