//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraIva
    {
        public int Id { get; set; }
        public string IdTipoComprobante { get; set; }
        public string PuntoVenta { get; set; }
        public int NumeroFactura { get; set; }
        public int AuxiliarNumero { get; set; }
        public string NumeroEmpresa { get; set; }
        public string Empesa { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Total { get; set; }
        public decimal Iva { get; set; }
        public decimal IvaAri { get; set; }
        public decimal IvaRes { get; set; }
        public decimal TotalIva { get; set; }
        public decimal Gasto { get; set; }
        public decimal Neto { get; set; }
        public string Especial { get; set; }
        public decimal Res { get; set; }
        public string IdTipoIva { get; set; }
        public string TipoFactura { get; set; }
        public decimal ResDgr { get; set; }
        public string Cuit { get; set; }
        public decimal dolar { get; set; }
        public string Diferencia { get; set; }
        public string Clase { get; set; }
        public string NombreEmple { get; set; }
        public string Periodo { get; set; }
        public string AbreviaturaFactura { get; set; }
        public int IdTipoMoneda { get; set; }
        public decimal Isib { get; set; }
        public int IdDiario { get; set; }
        public string Cae { get; set; }
        public decimal Impint { get; set; }
        public int IdImputacion { get; set; }
        public Nullable<decimal> Tnogra { get; set; }
        public Nullable<decimal> Texento { get; set; }
        public Nullable<decimal> PerGeneral { get; set; }
        public Nullable<decimal> Perib { get; set; }
        public Nullable<decimal> PerMun { get; set; }
        public Nullable<decimal> OtrosImpuestos { get; set; }
        public Nullable<decimal> Tnocat { get; set; }
        public Nullable<decimal> Pernac { get; set; }
        public Nullable<decimal> Iva27 { get; set; }
        public Nullable<decimal> Iva21 { get; set; }
        public Nullable<decimal> Iva105 { get; set; }
        public Nullable<decimal> Ivan5 { get; set; }
        public Nullable<decimal> Iva25 { get; set; }
        public Nullable<decimal> Total21 { get; set; }
        public Nullable<decimal> Total27 { get; set; }
        public Nullable<decimal> Total105 { get; set; }
        public Nullable<decimal> Total5 { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> Idusuario { get; set; }
        public Nullable<System.DateTime> UltimaModificacion { get; set; }
    }
}
