//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.ModeloDeDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCorrienteProveedorDetalles
    {
        public int IdProveedor { get; set; }
        public string RazonSocial { get; set; }
        public string Cbte { get; set; }
        public int PuntoVenta { get; set; }
        public int NumeroFactura { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> ImportePago { get; set; }
        public Nullable<decimal> TotalDolares { get; set; }
        public Nullable<decimal> Parcial { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public decimal Cotizacion { get; set; }
        public string NumeroPago { get; set; }
        public Nullable<int> Recibo { get; set; }
    }
}
