
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Datos.ModeloDeDatos
{

using System;
    using System.Collections.Generic;
    
public partial class Proveedor
{

    public int Id { get; set; }

    public string Nombre { get; set; }

    public Nullable<bool> Activo { get; set; }

    public string Cuit { get; set; }

    public string Direccion { get; set; }

    public Nullable<int> IdPais { get; set; }

    public Nullable<int> IdProvincia { get; set; }

    public string Telefono { get; set; }

    public Nullable<int> IdTipoIva { get; set; }

    public Nullable<int> DiasFactura { get; set; }

    public Nullable<int> IdImputacionProveedor { get; set; }

    public string Observaciones { get; set; }

    public Nullable<decimal> SaldoCuentaCorriente { get; set; }

    public string Email { get; set; }

    public Nullable<int> IdCodigoPostal { get; set; }

    public Nullable<int> IdAfipRegimen { get; set; }

    public Nullable<int> IdTipoProveedor { get; set; }

    public Nullable<int> IdImputacionFactura { get; set; }

    public Nullable<int> IdMonedaFactura { get; set; }

    public string DescripcionFactura { get; set; }

    public Nullable<int> IdTipoMoneda { get; set; }

    public Nullable<int> Perceptor { get; set; }

    public Nullable<decimal> MontoMinimo { get; set; }

    public Nullable<decimal> PorcentajePeceptor { get; set; }

    public Nullable<int> IdGrupoPresupuesto { get; set; }

    public Nullable<int> IdPuntoVenta { get; set; }

    public Nullable<int> IdUsuario { get; set; }

    public Nullable<System.DateTime> UltimaModificacion { get; set; }



    public virtual AfipRegimen AfipRegimen { get; set; }

    public virtual Imputacion Imputacion { get; set; }

    public virtual Imputacion Imputacion1 { get; set; }

    public virtual TipoIva TipoIva { get; set; }

    public virtual TipoMoneda TipoMoneda { get; set; }

    public virtual TipoProveedor TipoProveedor { get; set; }

    public virtual Pais Pais { get; set; }

    public virtual Provincia Provincia { get; set; }

}

}
